# Generated by Django 4.0.3 on 2022-03-11 01:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Specialdiet', models.CharField(max_length=50, null=True)),
                ('Mealtype', models.CharField(max_length=50, null=True)),
                ('preptime', models.CharField(max_length=50)),
                ('totaltime', models.CharField(max_length=50)),
                ('Ingredients', models.TextField(max_length=1000)),
                ('Directions', models.TextField(max_length=1000)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='employers.employer')),
            ],
        ),
    ]
